version: '2'
services:
  imcat:
    image: nobgr/vuln_imcat:v4.9
    depends_on:
      - mysql
    ports:
      - 80:80
  
  mysql:
    image: mysql:5.5
    ports: 
       - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 123456

